spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 11111111
    driver-class-name: com.mysql.jdbc.Driver